Remove use of global vars for current id and param name
influxdata/go-syslog pull request #51
Opened 2023-11-29 19:35 UTC by BenMatase

Fixes https://github.com/influxdata/go-syslog/issues/44

This avoids a race when trying to populate multiple SyslogMessages concurrently.

I've tested this out in a scenario with telegraf where we were seeing this issue frequently and now we don't.

2023-11-29 19:38 UTC, BenMatase commented
@leodido can't add you to reviewers

2023-11-29 19:57 UTC, leodido requested changes
You should apply those changes in the Ragel file (ie., `builder.go.rl` if I don't remember wrong). Then compile it in Go with the existing makefile.

2023-11-29 21:17 UTC, BenMatase commented
@leodido it changed a lot in the .go file. Is this error output the reason?
```
[bmatase@bmatase-mbp go-syslog (fix-global-var-race)]$ make build
ragel -I common -Z -G2 -e -o rfc5424/builder.go rfc5424/builder.go.rl
rfc5424/builder.go.rl:108:37: warning: applying plus operator to a machine that accepts zero length word
sed: -I or -i may not be used with stdin
make: *** [rfc5424/builder.go] Error 1
```

2023-11-29 21:32 UTC, BenMatase commented
I see the problem. Working on fixing it

2023-12-04 18:58 UTC, BenMatase commented
@leodido had some trouble with the `-i` aka inplace flags on my mac but I think it is in good shape now

2023-12-13 15:00 UTC, BenMatase commented
@leodido I believe I've addressed the changes you requested. Let me know if there is anything else you spot

2024-05-19 09:44 UTC, leodido commented
I don't have anymore write/maintain access here. So, I can't help/maintain it. It's unfortunate but it is what it is... Feel free to redirect this PR to https://github.com/leodido/go-syslog. I plan to keep evolving this project there, on my GitHub. Thank you

2024-05-21 19:17 UTC, closed without merging